version: 2
jobs:
  build_py3_requirements:
    working_directory: ~/alphacross
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run: sudo pip install pytest
      - run: python -m pytest
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results
          destination: tr1

