version: 2
jobs:
  build:
    working_directory: ~/alphacross
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run: sudo pip install -r requirements.txt
  test:
    working_directory: ~/alphacross
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run: pytest
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test

