version: 2
jobs:
  build:
    working_directory: ~/alphacross
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run: sudo pip install -r requirements.txt
      - run: cd $CIRCLE_WORKING_DIRECTORY/src/test/
      - run: pwd
      - run: python -m pytest

