version: 2
jobs:
  test:
    working_directory: ~/alphacross
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run: sudo pip install -r requirements.txt
      - run: python -m pytest

