## DO NOT EDIT THIS FILE
## Make a copy in the same folder, name it config.py and then edit it with your own variables and paths


DEBUG = 'True/False'
TEMPLATE_FOLDER = "your template folder (.html files)"
STATIC_FOLDER = "your static folder (.css, .js)"
PANE_TITLE = "AlphaCross"
MODEL_PATH = "your path to saved model (.h5)"
